artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Suvojeet-Haldar/data/raw/main/MasterDictionary-20240731T055414Z-001.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  unzip_data_dir: artifacts/data_ingestion/MasterDictionary


post_cleaning:
  root_dir: artifacts/data_ingestion
  positive_file_path: artifacts/data_ingestion/MasterDictionary/positive-words.txt
  negative_file_path: artifacts/data_ingestion/MasterDictionary/negative-words.txt



# model_trainer:
#   root_dir: artifacts/model_trainer
#   train_data_path: artifacts/data_transformation/train.csv
#   test_data_path: artifacts/data_transformation/test.csv
#   model_name: model.joblib



# model_evaluation:
#   root_dir: artifacts/model_evaluation
#   test_data_path: artifacts/data_transformation/test.csv
#   model_path: artifacts/model_trainer/model.joblib
#   metric_file_name: artifacts/model_evaluation/metrics.json